name: Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joshtynjala/setup-adobe-air-action@master
      - name: Windows Captive
        run: |
          Get-Command mxmlc
          Get-Command compc
          Get-Command adt
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joshtynjala/setup-adobe-air-action@master
      - name: Mac Captive
        run: |
          which mxmlc
          which compc
          which adt
  windows-air-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joshtynjala/setup-adobe-air-action@master
      - name: Win SWF
        with:
          air-version: "30.0"
      - name: Compile SWF
        run: |
          mxmlc -output bin/DemoAppGitHubActions.swf src/DemoAppGitHubActions.mxml
