name: Action AIR

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: joshtynjala/setup-adobe-air-action@master
        with:
          air-version: "33.1"
          accept-license: true
      - name: Windows Captive
        run: |
          Get-Command mxmlc
          Get-Command compc
          Get-Command adt -output bin/Test.exe src/DemoAppGitHubActions.mxml
#      - name: Upload asset to release
#        uses: gacts/upload-to-release@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          file: './hi' # No Idea on location of Project on VM?
#          type: 'application/octet-stream'
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joshtynjala/setup-adobe-air-action@master
        with:
          air-version: "33.1"
          accept-license: true
      - name: Mac Captive
        run: |
          which mxmlc
          which compc
          which adt
  #windows-air-version:
  #  runs-on: windows-latest
  # steps:
  #   - uses: actions/checkout@v2
  #   - uses: joshtynjala/setup-adobe-air-action@master
  #   - name: Win SWF
  #     run: |
  #       Line below throws an !!error!! when running Action
  #       mxmlc -output bin/DemoAppGitHubActions.swf src/DemoAppGitHubActions.mxml
